### ISSUE TITLE
Travisci/Heroku errors when processing master branch

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#140]
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:10:in `response_call': Expected(200) <=> Actual(422 Unprocessable Entity) (Heroku::API::Errors::RequestFailed)
body: "{\"limit\":1,\"size\":\"Free\",\"id\":\"cannot_run_above_limit\",\"error\":\"Cannot run more than 1 Free size dynos.\\n\\nRead more: https://devcenter.heroku.com/articles/dyno-size#default-scaling-limits\"}"
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.0/lib/heroku/api.rb:84:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.0/lib/heroku/api/processes.rb:20:in `post_ps'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/heroku/generic.rb:47:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:151:in `block (2 levels) in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:151:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:147:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:147:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/heroku/generic.rb:57:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by benichu** [comment]
does not seem to prevent automatic deploy to heroku... wait and see.
