### ISSUE TITLE
Build error on Travis CI at deployment

### ISSUE THREAD

**Issue by mathieugagne** [montrealrb/Montreal.rb#176]
Travis CI is complaining at deployment time.

[https://travis-ci.org/montrealrb/Montreal.rb](https://travis-ci.org/montrealrb/Montreal.rb)

This seems to be the culprit:
`InlineSvg::Configuration::Invalid: Asset Finder should implement the #find_asset method`

We can most likely reproduce by deploying straight to Heroku.

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       ** [Bugsnag] Bugsnag exception handler 2.8.13 ready, api_key=342f882cd8aa7229805871bf7e1ec1fe
       ** [Bugsnag] Notifying https://notify.bugsnag.com of InlineSvg::Configuration::Invalid from api_key 342f882cd8aa7229805871bf7e1ec1fe
       ** [Bugsnag] Notifying https://notify.bugsnag.com of InlineSvg::Configuration::Invalid from api_key 342f882cd8aa7229805871bf7e1ec1fe
       rake aborted!
       InlineSvg::Configuration::Invalid: Asset Finder should implement the #find_asset method
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/inline_svg-0.6.1/lib/inline_svg.rb:25:in `asset_finder='
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:15:in `block (2 levels) in <class:Railtie>'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/inline_svg-0.6.1/lib/inline_svg.rb:55:in `configure'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:12:in `block in <class:Railtie>'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in `call'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/config/environment.rb:5:in `<top (required)>'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/bugsnag-2.8.13/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_b99c1fc6da3ebcd34a953df678b9c52d/vendor/bundle/ruby/2.2.0/gems/bugsnag-2.8.13/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       ** [Bugsnag] Waiting for 1 outstanding request(s)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app
```

**Comment by steakunderscore** [comment]
[See this PR](https://github.com/thoughtbot/administrate/pull/365) on the administrate gem.

**Comment by steakunderscore** [comment]
Added patch for this: [pull#182](pull#182)

**Comment by steakunderscore** [comment]
This can be closed now.
